// src/main/frontend/src/components/Diff.vue
<template xmlns:v-slot="http://www.w3.org/1999/XSL/Transform">
    <v-card class="xs12" min-height="95vh" min-width="100%">
        <v-card-text>
            <v-dialog v-model="open">
                <v-card>
                    <editor
                            id="diff-editor"
                            :diffEditor="true"
                            :original="original"
                            v-model="patched"
                            theme="vs-dark"
                            language="javascript"
                            height="400"
                            :options="{ readOnly: true, automaticLayout: true }"
                    ></editor>
                    <v-list disabled dense>
                        <v-list-item v-for="(c,i) in changes" :key="i">
                            <v-list-item-icon>
                                <v-icon>{{iconFor(c.subject)}}</v-icon>
                                <v-icon :color="colorFor(c.type)">{{iconFor(c.type)}}</v-icon>
                            </v-list-item-icon>
                            <v-list-item-content>
                                <v-list-item-title>
                                    <span class="subject">{{c.subject}} </span>
                                    <span class="old">{{c.oldValue}}</span>
                                    <span v-if="c.oldValue"><v-icon>{{icons.arrowRight}}</v-icon></span>
                                    <span class="new">{{c.newValue}}</span>
                                </v-list-item-title>
                            </v-list-item-content>
                        </v-list-item>
                    </v-list>
                </v-card>
            </v-dialog>
        </v-card-text>
    </v-card>
</template>

<script>
    import editor from 'monaco-editor-vue';
    import {
        mdiArrowRight,
        mdiCodeBraces,
        mdiLabelOff,
        mdiMinusBox,
        mdiNotEqual,
        mdiPlusBox,
        mdiSwapVertical,
        mdiVariable
    } from '@mdi/js'


    export default {
        components: {editor},
        props: {
            changes: {
                type: Array,
                required: true,
            },
            original: {
                type: String,
                required: false,
                default: ""
            },
            patched: {
                type: String,
                required: false,
                default: ""
            },
            show: {
                required: true,
                default: false
            }
        },
        data: () => {
            return {
                icons: {
                    CHANGE_FIELD: mdiVariable,
                    CHANGE_FIELD_VERSION: mdiLabelOff,
                    CHANGE_FIELD_TYPE: mdiCodeBraces,
                    CHANGE_FIELD_DEFAULT: mdiNotEqual,
                    ADD_FIELD: mdiPlusBox,
                    CHANGE_TYPE: mdiCodeBraces,
                    REMOVE_FIELD: mdiMinusBox,
                    MOVE_FIELD: mdiSwapVertical,
                    arrowRight: mdiArrowRight,
                }
            }
        },
        computed: {
            open: {
                get() {
                    return this.show
                },
                set(newVal) {
                    if (!newVal) this.$emit('close')
                }
            }
        },
        watch: {
            show() {
                this.open = this.show
            }
        },

        methods: {
            iconFor(type) {
                return this.icons[type]
            },
            colorFor(type) {
                switch (type) {
                    case "CHANGE_FIELD":
                    case "CHANGE_FIELD_VERSION":
                    case "CHANGE_FIELD_TYPE":
                    case "CHANGE_FIELD_DEFAULT":
                    case "MOVE_FIELD":
                        return 'warning';
                    case "ADD_FIELD":
                        return 'primary';
                    case "CHANGE_TYPE":
                    case "REMOVE_FIELD":
                        return 'error';
                }
            }
        },

        mounted() {

        }
    }
</script>
<style>
    .subject {
        font-weight: bold;
    }
    .old {
        text-decoration: line-through;
        color: grey;
    }
</style>

// src/main/frontend/src/components/Diff.svelte
<script>
	import { mdiArrowRight, mdiCodeBraces, mdiLabelOff, mdiMinusBox, mdiNotEqual, mdiPlusBox, mdiSwapVertical, mdiVariable } from '@mdi/js'
	import Card from "svelte-materialify/src/components/Card";
	import CardActions from "svelte-materialify/src/components/Card/CardActions.svelte";
	import CardText from "svelte-materialify/src/components/Card/CardText.svelte";
	import CardTitle from "svelte-materialify/src/components/Card/CardTitle.svelte";
	import Dialog from "svelte-materialify/src/components/Dialog";
	import Icon from "svelte-materialify/src/components/Icon";
	import List from "svelte-materialify/src/components/List";
	import ListItem from "svelte-materialify/src/components/List/ListItem.svelte";
	import Textarea from "svelte-materialify/src/components/Textarea";

	export let oldSpec;
	export let newSpec;
	export let changes;
	export let showDiffDialog;

	const icons = Object.freeze({
        CHANGE_FIELD: mdiVariable,
        CHANGE_FIELD_VERSION: mdiLabelOff,
        CHANGE_FIELD_TYPE: mdiCodeBraces,
        CHANGE_FIELD_DEFAULT: mdiNotEqual,
        ADD_FIELD: mdiPlusBox,
        CHANGE_TYPE: mdiCodeBraces,
        REMOVE_FIELD: mdiMinusBox,
        MOVE_FIELD: mdiSwapVertical,
        arrowRight: mdiArrowRight,
	});
	const iconFor = (type) => icons[type];
    const colorFor = (type) => {
        switch (type) {
            case "CHANGE_FIELD":
            case "CHANGE_FIELD_VERSION":
            case "CHANGE_FIELD_TYPE":
            case "CHANGE_FIELD_DEFAULT":
            case "MOVE_FIELD":
                return 'warning';
            case "ADD_FIELD":
                return 'primary';
            case "CHANGE_TYPE":
            case "REMOVE_FIELD":
                return 'error';
        }
	}
</script>

<Dialog bind:active={showDiffDialog}>
	<Card>
		<CardTitle>Diff:</CardTitle>
		<CardText>
			<Textarea outlined value={oldSpec} readonly>Old Specification</Textarea>
			<Textarea outlined value={newSpec} readonly>New Specification</Textarea>
			<List disabled dense>
				{#each changes as change}
					<ListItem>
						<Icon class="{colorFor(change.type)}-text" path={iconFor(change.type)}/>
						<span class="subject">{change.subject} </span>
						{#if change.oldValue && change.newValue}
							<span class="old">{change.oldValue}</span>
							<Icon path={icons["arrowRight"]}/>
							<span class="new">{change.newValue}</span>
						{/if}
					</ListItem>
				{/each}
			</List>
		</CardText>
		<CardActions>
			<slot/>
		</CardActions>
	</Card>
</Dialog>

<style>
	.subject {
        font-weight: bold;
    }
    .old {
        text-decoration: line-through;
        color: grey;
    }
</style>
